#ifndef QSOCKETSERVER_GLOBAL_H
#define QSOCKETSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QSOCKETSERVER_LIBRARY)
#  define QSOCKETSERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QSOCKETSERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QSOCKETSERVER_GLOBAL_H
